### ISSUE TITLE
大佬有没有个简易的dns服务端放在服务器上，正好搭配用来做真实延迟测试，icmp延迟太假了

### ISSUE THREAD

**Issue by 1265578519** [fakeboboliu/simpleDnsDelayTester#1]
大佬有没有个简易的dns服务端放在服务器上，正好搭配用来做真实延迟测试，icmp延迟太假了

**Comment by fakeboboliu** [comment]
那样的话我个人建议还是直接 tcping…毕竟 dns over udp 无论运营商还是过墙都太危险了

如果你觉得不是问题的话我推荐 adguardhome，只用来测延迟的话可以给对应域名写个 hosts 让 adg home 直接返回 ip
